// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAKpLA3gRhoMU1z8cm6S1Czq_3XrtT61o',
    appId: '1:492796542773:web:dbf40c63293612d82a567c',
    messagingSenderId: '492796542773',
    projectId: 'convo-14c4d',
    authDomain: 'convo-14c4d.firebaseapp.com',
    storageBucket: 'convo-14c4d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhwqQson5r6beEhCc4n3r7kVL4HfQx4og',
    appId: '1:492796542773:android:28f17865006f819a2a567c',
    messagingSenderId: '492796542773',
    projectId: 'convo-14c4d',
    storageBucket: 'convo-14c4d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3lbtY9gt3Ej9xaXIc74bDXGnMOZDm-Lw',
    appId: '1:492796542773:ios:6243c976e34636092a567c',
    messagingSenderId: '492796542773',
    projectId: 'convo-14c4d',
    storageBucket: 'convo-14c4d.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3lbtY9gt3Ej9xaXIc74bDXGnMOZDm-Lw',
    appId: '1:492796542773:ios:6243c976e34636092a567c',
    messagingSenderId: '492796542773',
    projectId: 'convo-14c4d',
    storageBucket: 'convo-14c4d.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAKpLA3gRhoMU1z8cm6S1Czq_3XrtT61o',
    appId: '1:492796542773:web:85fb944fd4675e482a567c',
    messagingSenderId: '492796542773',
    projectId: 'convo-14c4d',
    authDomain: 'convo-14c4d.firebaseapp.com',
    storageBucket: 'convo-14c4d.appspot.com',
  );

}